/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package exercise6;

/**
 *
 * @author ASUSuser
 */
public class Exer6 extends javax.swing.JFrame {

    /** Creates new form Exer6 */
    public Exer6() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x70 = new javax.swing.JButton();
        Persona = new javax.swing.JButton();
        Saga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DisplayProton = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoProton = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        x70.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUSuser\\Desktop\\proton-X70-logo-vector.png")); // NOI18N
        x70.setText("jButton1");
        x70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x70ActionPerformed(evt);
            }
        });

        Persona.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUSuser\\Desktop\\Proton-Persona-2019-Logo-Vector.png")); // NOI18N
        Persona.setText("jButton1");
        Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonaActionPerformed(evt);
            }
        });

        Saga.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUSuser\\Desktop\\proton-saga-new-vector-logo.png")); // NOI18N
        Saga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SagaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercise6/PROTON_Holdings_logo_(2019–present).png"))); // NOI18N
        jLabel1.setLabelFor(jLabel1);
        jLabel1.setText("jLabel1");

        DisplayProton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayProtonActionPerformed(evt);
            }
        });

        InfoProton.setColumns(20);
        InfoProton.setRows(5);
        jScrollPane1.setViewportView(InfoProton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Saga, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x70, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DisplayProton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Saga, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(x70, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DisplayProton)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SagaActionPerformed
        String test;
        
        test=("Model: Proton Saga | RM32,000.00");
        DisplayProton.setText(test);
        
        InfoProton.setText("Proton Saga: "
                + "\n\nBasic Salary: RM1,500"
                + "\n\nMonthly Installment: RM400"
                + "\n\nSPECIFICATION"
                + "\nVarian: 1.3 Standard MT/AT | Premium AT"
                + "\nTransmission Type: 5-Speed Manual | 4-Speed Automatic"
                + "\nEngine Type: 4 Cylinder In-Line,  16 Valve Dohc, VVT"
                + "\nDisplacement(cc): 1.332"
                + "\nFuel Tank Capacity: 40 L"
                + "\n\nSafety Feature: \t\r\n1.Front SRS Airbags \n2.Anti-Lock Braking System (ABS) \n3.Electronic Brake Distribution (EBD)"
                + "\n\nAccessories: \n1.7 inch Touch Screen Monitor \n2.Leather Seat");    }//GEN-LAST:event_SagaActionPerformed

    
    private void PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonaActionPerformed
        String test;
        
        test=("Model: Proton Persona | RM42,600.00");
        DisplayProton.setText(test);
        
        InfoProton.setText("Proton Persona: "
                + "\n\nBasic Salary: RM2,500"
                + "\n\nMonthly Installment: RM500"
                + "\n\nSPECIFICATION"
                + "\nVarian: 1.6 Standard MT/CVT | Executive Premium CVT"
                + "\nTransmission Type: 5-Speed Manual | 4-Speed Automatic"
                + "\nEngine Type: 4 Cylinder In-Line,  16 Valve Dohc, VVT"
                + "\nDisplacement(cc): 1.597"
                + "\nFuel Tank Capacity: 40 L"
                + "\n\nSafety Feature: \t\r\n1.Front SRS Airbags \n2.Anti-Lock Braking System (ABS) \n3.Electronic Brake Distribution (EBD)"
                + "\n\nAccessories: \n1.8 inch Touch Screen Monitor \n2.Leather Seat \n3.Daylight Running LED");
    }//GEN-LAST:event_PersonaActionPerformed

    private void DisplayProtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayProtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayProtonActionPerformed

    private void x70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x70ActionPerformed
        String test;
        
        test=("Model: Proton x70 | RM36,700.00");
        DisplayProton.setText(test);
        
        InfoProton.setText("Proton x70: "
                + "\n\nBasic Salary: RM3,500"
                + "\n\nMonthly Installment: RM1000"
                + "\n\nSPECIFICATION"
                + "\nVarian: 1.6 TGHDI Standard 2WD | Executive 2WD | Premium X"
                + "\nTransmission Type: 7-Speed Dual Clutch with Manual Mode"
                + "\nEngine Type: 4 Cylinder In-Line,  16 Valve Dohc, TGHDI"
                + "\nDisplacement(cc): 1.799"
                + "\nFuel Tank Capacity: 60 L"
                + "\n\nSafety Feature: \t\r\n1.6 SRS Airbags (Front, Side & Curtain) \n2.Anti-Lock Braking System (ABS) \n3.Electronic Brake Distribution (EBD) \n4.Auto Brake Hold \n5.Traction Control System(TCS)"
                + "\n\nAccessories: \n1.7 inch Touch Screen Monitor \n2.Leather Seat \n3.Daylight Running LED \n4.Panoramic Sunroof");    }//GEN-LAST:event_x70ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exer6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exer6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exer6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exer6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exer6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DisplayProton;
    private javax.swing.JTextArea InfoProton;
    private javax.swing.JButton Persona;
    private javax.swing.JButton Saga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton x70;
    // End of variables declaration//GEN-END:variables

    private static class txtrDisplay {

        private static void setText(String proton_Persona_) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public txtrDisplay() {
        }
    }

}
